### ISSUE TITLE
group/add-member what id is used

### ISSUE THREAD

**Issue by arj03** [ssbc/ssb-meta-feeds-group-spec#3]
context I'll put out a spec that goes into these IDs in more detail and was looking at this repo

We need to pin down exactly what ID we use in group/add-member.

Classic main id:

Pros: used everywhere else
Cons: the group could easily outlive the classic feed, so we need to always remember peoples classic ids

Metafeed root id:

Pros: should be stable, might make it easier to replicate for people outside your hops range
Cons: is the first time we don't use classic id, on the other hand only people with metafeeds will be able to use groups anyway

**Comment by staltz** [comment]
Yeah I would prefer to point to the root mf ID, because, as you said,

> only people with metafeeds will be able to use groups anyway

Main feed should **only** be used wherever backwards compatibility is important.

**Comment by staltz** [comment]
Done by commit https://github.com/ssbc/ssb-meta-feeds-group-spec/commit/bb3a30b2ce51c098db99bde8c1b8cf51bc83be63
